### ISSUE TITLE
Node.js/Next.jsアプリケーション向けGitHub Actions CI/CD対応

### ISSUE THREAD

**Issue by Hondy000** [Hondy000/claude-code-playground#7]
# Node.js/Next.jsアプリケーション向けGitHub Actions CI/CD対応

## 概要
Next.js + TypeScriptアプリケーションのための包括的なCI/CDパイプラインをGitHub Actionsで構築する。

## 背景
- 既存のPython向けGitHub Actionsは整備済み
- Node.js/Next.jsアプリケーション追加に伴い、対応するCI/CDが必要
- フロントエンドアプリケーション特有のビルドとテストプロセスに対応

### 1. Node.js CI/CD ワークフロー (.github/workflows/nodejs-tests.yml)
```yaml
name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/nextjs-app/**'
      - '.github/workflows/nodejs-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/nextjs-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
```

### 2. 主要なチェック項目
- [ ] **依存関係のインストール**
  - npm ci による再現可能なインストール
  - キャッシュの活用
  
- [ ] **コード品質チェック**
  - ESLintによる静的解析
  - Prettierによるフォーマットチェック
  - TypeScript型チェック

- [ ] **テスト実行**
  - Jestによるユニットテスト
  - React Testing Libraryによるコンポーネントテスト
  - カバレッジレポート生成

- [ ] **ビルドチェック**
  - Next.js本番ビルド
  - バンドルサイズ分析
  - Lighthouse CI（パフォーマンス測定）

#### a. Next.js特化ワークフロー
- [ ] 静的サイト生成（SSG）のチェック
- [ ] API Routesのテスト
- [ ] 画像最適化の検証

#### b. セキュリティスキャン
- [ ] npm auditによる脆弱性チェック
- [ ] Dependabotとの連携
- [ ] ライセンスチェック

#### c. デプロイメント準備
- [ ] Vercelへの自動デプロイ（Preview/Production）
- [ ] Dockerイメージのビルドとプッシュ
- [ ] アーティファクトの保存

### 4. パフォーマンス最適化
- [ ] 並列ジョブ実行
- [ ] マトリックスビルド（複数Node.jsバージョン）
- [ ] 条件付き実行（変更ファイルに基づく）

## 統合ワークフロー (.github/workflows/all-tests.yml)
```yaml
name: All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    uses: ./.github/workflows/python-tests.yml
  
  nodejs:
    uses: ./.github/workflows/nodejs-tests.yml
  
  integration:
    needs: [python, nodejs]
    runs-on: ubuntu-latest
```

## 期待される効果
- コード品質の自動保証
- 早期バグ発見
- 一貫性のあるビルドプロセス
- 開発者の生産性向上
- デプロイメントの信頼性向上

## タスク
- [ ] Node.js用GitHub Actionsワークフロー作成
- [ ] ESLint/Prettier設定との連携
- [ ] テストカバレッジレポートの統合
- [ ] ビルド成果物の管理設定
- [ ] Vercelデプロイメント連携
- [ ] READMEへのバッジ追加

## 参考情報
- [GitHub Actions for Node.js](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs)
- [Next.js Deployment](https://nextjs.org/docs/deployment)
- [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci)

## ラベル
- ci/cd
- github-actions
- nodejs
- nextjs
- automation
